### ISSUE TITLE
Show a meaningful error message if required ENV variables are missing

### ISSUE THREAD

**Issue by sergeil** [whaler/whaler-client#1]
Faced a problem when whaler commands are by Monit, the thing that although Monit runs by default from a root user it doesn't export some necessary env variables which makes whaler crush with giving some gibberish like this:

```
docker: Error response from daemon: Invalid volume spec ":": volumeinvalid: Invalid volume specification: ':'.
See '/usr/bin/docker run --help'.
```

Eventually we managed to figure out that simply "HOME" env variable is not exported automatically and fix this in proxy bash script by exporting it manually but it would have saved a lot of time if whaler would have showed a meaningful error message when required ENV variables are missing or incorrect.

**Comment by cravler** [comment]
done
